# DigitalOcean App Platform Configuration for BHM Hockey
#
# IMPORTANT: This is for App Platform, NOT Functions!
# Create your app at: https://cloud.digitalocean.com/apps
#
# Deploy: doctl apps create --spec .do/app.yaml
# Update: doctl apps update YOUR_APP_ID --spec .do/app.yaml
#
# If DO auto-detects "Functions" components, DELETE them and only keep the Docker service.

name: bhmhockey
region: nyc

# Managed PostgreSQL Database
databases:
  - engine: PG
    name: bhmhockey
    num_nodes: 1
    size: db-s-dev-database  # $15/month, upgrade to db-s-1vcpu-1gb for production
    version: "15"

# .NET 8 API Service
services:
  - name: api
    github:
      repo: adilp/bhmHockeyv3
      branch: main
      deploy_on_push: true

    # Build configuration - Monorepo structure
    source_dir: apps/api
    dockerfile_path: apps/api/Dockerfile

    # HTTP configuration
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month, upgrade to basic-s for production

    # Ingress routing configuration
    # CRITICAL: Controllers must use [Route("[controller]")] for this to work!
    # DO ingress adds /api prefix, so /api/auth -> container receives /api/auth
    # With preserve_path_prefix: true, controller route /auth matches /api/auth
    routes:
      - path: /api
        preserve_path_prefix: true  # Keeps /api in the path when routing
      - path: /health
      - path: /

    # Health check configuration
    health_check:
      http_path: /health
      initial_delay_seconds: 60  # Allow time for EF migrations on cold start
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      # .NET Core configuration
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080

      # Database connection (from managed database)
      # Program.cs must convert DATABASE_URL format to .NET connection string
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${bhmhockey.DATABASE_URL}

      # JWT Configuration
      # Generate secret: openssl rand -base64 32
      - key: Jwt__Secret
        scope: RUN_TIME
        type: SECRET
        value: REPLACE_IN_DO_CONSOLE_WITH_SECURE_32_CHAR_SECRET
      - key: Jwt__Issuer
        scope: RUN_TIME
        value: https://${APP_DOMAIN}
      - key: Jwt__Audience
        scope: RUN_TIME
        value: https://${APP_DOMAIN}
      - key: Jwt__ExpiryMinutes
        value: "10080"  # 7 days

      # CORS Configuration
      - key: Cors__AllowedOrigins
        scope: RUN_TIME
        value: https://${APP_DOMAIN}

      # Expo Push Notifications (optional - set in DO console)
      # - key: Expo__AccessToken
      #   scope: RUN_TIME
      #   type: SECRET
      #   value: SET_IN_DO_CONSOLE
